pr:
  autoCancel: true

jobs:
- job: 'flake'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
    maxParallel: 1

  steps:
  - bash: echo "##vso[task.prependpath]/usr/share/miniconda/bin"
    displayName: Add conda to PATH
  - template: .azure-pipelines/setup.yml
  - bash: |
      source activate foo
      flake8 --ignore=E501,E722 --exclude docs/conf.py .
    displayName: flake8

- job: 'CI_tests'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
    maxParallel: 1

  steps:
  - bash: echo "##vso[task.prependpath]/usr/share/miniconda/bin"
    displayName: Add conda to PATH
  - template: .azure-pipelines/setup.yml
  - bash: |
      source activate foo
      ./.ci_stuff/test_dag.sh
    displayName: "CI test"

- job: 'docs'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
    maxParallel: 1

  steps:
  - bash: echo "##vso[task.prependpath]/usr/share/miniconda/bin"
    displayName: Add conda to PATH
  - template: .azure-pipelines/setup.yml
  - bash: |
      source activate foo
      cd docs
      make html
    displayName: "make docs"

- job: 'envs'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
    maxParallel: 1

  steps:
  - bash: echo "##vso[task.prependpath]/usr/share/miniconda/bin"
    displayName: Add conda to PATH
  - template: .azure-pipelines/setup.yml
  - bash: |
      source activate foo
      snakePipes createEnvs
    displayName: "createEnvs"

- job: 'envs_OSX'
  pool:
    vmImage: 'macOS-latest'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
    maxParallel: 1

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
  - bash: sudo chown -R $USER $CONDA
    displayName: Take ownership of conda installation
  - bash: |
      if [ -f /Users/vsts/.conda/pkgs/urls.txt ]; then
        echo "chown"
        sudo chown 501:20 /Users/vsts/.conda/pkgs/urls.txt
      fi
    displayName: Fix OSX permissions
  - template: .azure-pipelines/macosx_setup.yml
  - bash: |
      source activate foo
      sudo snakePipes createEnvs
    displayName: "createEnvs"
