################################################################################
# Please comment out and adjust the following configuration variables if their
# default values are not appropriate for your input data
################################################################################
## paired-end read name extension (default: ["_R1", "_R2"])
# reads: ["_R1", "_R2"]

## FASTQ file extension (default: ".fastq.gz")
# ext: ".fastq.gz"

## Mate orientation in paired-end experiments for Bowtie2 mapping
## (default "--fr" is appropriate for Illumina sequencing)
# mate_orientation: "--fr"

## Median/mean fragment length, only relevant for single-end data (default: 200)
# fragment_length: 200

## Options to TrimGalore (default: "--stringency 2")
# trim_options: "--stringency 2"



################################################################################
# The following configuration variables can only be set via this configuration
# file when calling snakemake directly, i.e. without using the wrapper script
# DNA-mapping. When calling the script DNA-mapping, the values set below are
# ignored.
# example call: snakemake --snakefile /path/to/snakemake_workflows/workflows/DNA-mapping/Snakefile
#                         --cores 32
#                         --configfile /path/to/snakemake_workflows/workflows/DNA-mapping/example.config.yaml
#                         --directory /path/to/outputdir
################################################################################
## Snakemake workflow directory
# maindir: /home/heyne/install/snakemake_workflows/scRNAseq
## Input directory with FASTQ files
# indir: /home/heyne/projects/scRNAseq/fastq_head/
## Genome acronym
# genome: mm10
## Number of reads to downsample from the head of each FASTQ file
# downsample: 50000
## Trim reads with TrimGalore
# trim: True
## Run FASTQC read quality control
# fastqc: True
## Retain only de-duplicated reads/read pairs
# dedup: True
## Retain only reads mapping in proper pairs
# properpairs: True
## Retain only reads with at least the given mapping quality
# mapq: 1
## Bin size of output files in bigWig format
# bw_binsize: 10
## Run computeGCBias quality control
# gcbias: False
##  Verbose output
# verbose: True
