package:
  name: snakepipes
  version: 2.0.2

source:
  path: ../

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3
  run:
    - python >=3
    - snakemake >=5.7
    - pandas
    - graphviz
    - fuzzywuzzy
    - pyyaml >=5.1
    - coreutils

test:
  commands:
    - DNA-mapping --help

about:
  home: 'https://snakepipes.readthedocs.org'
  license: MIT
  summary: NGS processing pipelines from the MPI-IE
  license_file: LICENSE
