################################################################################
# Please specify all ChIP samples plus their matching control/chromatin input
# sample.
# Specify for each ChIP sample whether the IP target results in broad/mixed-type
# enrichment (most histone marks, e.g. H3K4me1, H3K36me3, H3K9me3, H3K27me3)
# or not. In the latter case, the enrichment is instead punctuate/narrow
# (e.g. TFs, active histone marks as H3K27ac or H3K4me3).
#
# Example:
# chip_dict:
#   my_H3K27ac_sample:
#     control: my_Input_sample
#     broad: False
#   my_H3K27me3_sample:
#     control: my_Input_sample
#     broad: True
#
# IMPORTANT: Use only whitespace, but NO TAB indentation in this YAML file!
################################################################################
chip_dict:
  my_H3K27ac_sample:
    control: my_Input_sample
    broad: False
  my_H3K27me3_sample:
    control: my_Input_sample
    broad: True


################################################################################
# Please comment out and adjust the following configuration variables if their
# default values are not appropriate for your input data
# ################################################################################
## Median/mean fragment length, only relevant for single-end data (default: 200)
# fragment_length: 200
## Genome acronym
# genome: hs37d5
## Input data is paired-end
# paired: True
## Bin size of output files in bigWig format
# bw_binsize: 10
##  Verbose output
# verbose: True

################################################################################
# Calling snakemake directly, i.e. without using the wrapper script:
# example call: 
# snakemake --snakefile /path/to/snakemake_workflows/workflows/ChIP-seq/Snakefile
#           --configfile /path/to/snakemake_workflows/workflows/ChIP-seq/example.config.yaml
#           --directory /path/to/outputdir
#           --cores 32
################################################################################

