name: snakepipes_scRNAseq_environment_0.1
channels:
 - bioconda
 - conda-forge
dependencies:
 - bedtools=2.27.1
 - ucsc-genepredtogtf=357
 - ucsc-bedtogenepred=357
 - ucsc-genepredtobed=357
 - ucsc-gtftoGenepred=357
 - subread=1.6.1
 - star=2.6.0b
 - r-base=3.4.1
 - r-dplyr=0.7.4
 - r-ggplot2=2.2.1
 - bioconductor-biomart=2.34.2
